import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "CodeBuck | About Page",
    description: "Generated by create next app",
  };

const LayoutAbout = ({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>)  => {
  return (
    children
  )
}

export default LayoutAbout
